### ISSUE TITLE
error: Unable to write to /sys/class/gpio/gpio117/value

### ISSUE THREAD

**Issue by jerwij** [kkeller/Nokia5110#3]
Dear Sir,
I'am trying to run the testfile but it doesn't work. I use the Debian 9.3 2018-03-05 4GB SD IoT distribution and i  get the following error's:

info: No pinmux for P9_25
error: Unable to write to /sys/class/gpio/gpio117/value
error: Unable to write to /sys/class/gpio/gpio117/value
/usr/local/lib/node_modules/bonescript/src/index.js:325
            if(bitOrder == b.LSBFIRST) {
                           ^

ReferenceError: b is not defined
  at Object.f.shiftOut (/usr/local/lib/node_modules/bonescript/src/index.js:325:28)
  at Object.exports.write (/var/lib/cloud9/Jeroen/nokia5110/LCD_5110.js:99:7)
  at Object.exports.setup (/var/lib/cloud9/Jeroen/nokia5110/LCD_5110.js:60:13)
  at Object.<anonymous> (/var/lib/cloud9/Jeroen/nokia5110/nokia5110Test.js:19:5)
  at Module._compile (module.js:577:32)
  at Object.Module._extensions..js (module.js:586:10)
  at Module.load (module.js:494:32)
  at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Timeout.Module.runMain [as _onTimeout] (module.js:611:10)
  at ontimeout (timers.js:386:11)
  at tryOnTimeout (timers.js:250:5)
  at Timer.listOnTimeout (timers.js:214:5)

How can I fix this?

Best regards,
Jeroen

**Comment by kkeller** [comment]
Sorry, I'm unable to help you with this. I no longer am using BeagleBone development boards or the NodeJS development environment.

The main person that supports things like this on BeagleBone development boards is Jason Kridner. He has forked this repository and has added some code to support later versions of NodeJS and BeagleBone development boards.

See:  https://github.com/jadonk/Nokia5110

NOTE: All this code assumes you are using a BeagleBone development board. If not, you'll have to use this code  and bonescript as an example and port it all over to your hardware. 

- Ken -

PS: Well I couldn't help but look a little at the errors that you listed. I'm guessing that it is a compatibility error with bonescript and the version of Linux you are using. I say this because you are getting errors saying unable to write to the Sysfs filesystem in the **bonescript/src/index.js** file. I'm guessing that the Sysfs interface has changed and bonescript has not been updated...  BUT only a guess...
